### PR TITLE
Add new update method

### PR DESCRIPTION
**Pull request by thierryskoda**
I'm currently using Prisma for my backend and sometimes, the `save` function doesn't work because my `datamodel` doesn't provide a `where`-`data` input.

Example:
I have a project node which has a building and that building has an address. When I want to update my project, the data specified can accept something like this:
````
building: {
   update: {
      address: {
         ...
      }
   }
}
````

But the current `save` method is doing something like this:
````
building: {
   update: {
      where: {
      },
      data: {
      }
   }
}
````

I called the new method `update`. I'm not sure if that's the best name but I couldn't think of any better name for the moment.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Interesting, I've looked into my own Prisma graphql code and you're right, Prisma doesn't have a `{ where: {...}, data: {...} }` type when the relation is singular. But when it's a to-many relation (so an array), it always has `where` and `data`.

So, this is actually a bug in the current `save` implementation. In [these lines](https://github.com/Volst/graphql-form-helpers/blob/17913d01de72791442ae0c291fec9e5ad7f918b6/src/formatters/save.ts#L37-L41), it shouldn't add `where` and `data`.

Does this also fix your use-case? And if so, could you fix that bug and remove the `dist/` files and revert the `.gitignore` changes?

**Comment by SpaceK33z** [comment]
Thanks! It should be `output.update = values` though (object cloning is not necessary because we already deep clone in [this line](https://github.com/Volst/graphql-form-helpers/blob/17913d01de72791442ae0c291fec9e5ad7f918b6/src/parseFormToMutation.ts#L12)). The tests are failing currently because the "save - accept object" test should be updated with the new output.

**Comment by thierryskoda** [comment]
Oh yeah. Sorry about that. Trying to do things too quickly!

**Comment by SpaceK33z** [comment]
Perfect, thanks again! Published in `@volst/graphql-form-helpers@0.2.5`.

**Pull request merged**
